### ISSUE TITLE
January Nodeschool

### ISSUE THREAD

**Issue by gangleri** [nodeschool/belfast#1]
@panloaf lets discuss here. 

What have you guys got organised so far?

**Comment by panloaf** [comment]
Dead on - can we add the January 21st date for Nodeschool, as it's already booked?

**Comment by gangleri** [comment]
Yeah of course, I have added you as a contributor. Do you want to add the event?

**Comment by panloaf** [comment]
Sure - thanks!

Currently organised is the venue and @d3z's assistance.  The plan was to run an open workshop using the nodeschool material and providing mutual mentor support, rather than having a 'teacher-led' prescriptive course to follow.  I will be pushing out more information via the @FarsetLabs Facebook/Twitter and NI Tech Slack channel to get the word out initially - possibly also via @syncNI.

Would you or @lanazwart be available to participate on the 21st?

**Comment by gangleri** [comment]
Yeah I'll be there and sure everyone else will be. My hope would be to make this monthly or bimonthly depending on interest

**Comment by panloaf** [comment]
Brilliant! Glad to see this is coming together, as it's pretty timely for me :)

**Comment by panloaf** [comment]
I've added the change as a PR.  I'll create a Facebook event via the Farset page tomorrow morning, though it would be good to see if there's enough response to use Meetup or similar.

Thanks for the quick response, Alan.  I look forward to speaking to you in person :)

**Comment by gangleri** [comment]
It's merged thanks for doing that.

Yeah I was in two minds about a meetup group, thought if we could do without it, its one less thing to pay for

**Comment by gangleri** [comment]
@panloaf @lanazwart @chrisfowler @ablair08 @d3z 
How about we all get together and grab tea sometime next week so that we get a chance to meet before this event?

**Comment by chrisfowler** [comment]
Hey Alan,

Tea would be good. I'm back in on 7th so anytime after that for me. 21st is
ok for me too. Looking forward to meeting everyone.

Have a great New Year's Eve!!

Chris

**Comment by gangleri** [comment]
Thank @chrisfowler will get together around that. 

Have a great New Year's too.

**Comment by ablair08** [comment]
Looking forward to it. I am back on Monday 4th.

**Comment by gangleri** [comment]
@panloaf have you been recording registration anywhere before now?

What is the maximum number of people that can attend an event in FarSet? I have setup a tito account, it's free but will allow us to limit the tickets available. 

If people DM me their email address I will add them as moderators on tito

**Comment by bmullan91** [comment]
Hey @gangleri @panloaf etc.. I'd be up for helping out / mentoring if you folk need a hand :)

**Comment by gangleri** [comment]
Thanks @bmullan91 the more the merrier :) 

Are you able to meet up with us sometime, still trying to agree a date/time that suits everyone

**Comment by bmullan91** [comment]
@gangleri yep, sounds good :+1:

**Comment by gangleri** [comment]
@bmullan91 excellent, keep an eye on this issue and we'll announce date/time/venue probably some evening after work so that we get a chance to meet each other before the event

**Comment by panloaf** [comment]
@gangleri I haven't been recording registration anywhere so far, as I wasn't expecting space to be an issue, but Tito looks like a good solution.  Farset normally use GetInvited.to for ticketing events, but I thought that might be overkill for a free open workshop.

Farset can accommodate up to 50 in a workshop layout (seated at desks) in the main Event Space, and a good deal more for theatre-style seating - the limit is more the number of physical seats available at that point :)

**Comment by d3z** [comment]
Firstly, thanks for everyone who picked up the ball that I dropped in getting this off the ground. I'll be of whatever help I can be. If you want to get together next week IRL for a chat, I'm all for that.

**Comment by gangleri** [comment]
Unless anybody has a better suggestion how about meeting this Thursday (7th Jan) 6pm Café Nero in Europa bus depot

**Comment by lanazwart** [comment]
Suits me.

**Comment by d3z** [comment]
That should work for me.

**Comment by bmullan91** [comment]
Me too.

**Comment by panloaf** [comment]
Works for me - that's on my journey home :)

**Comment by chrisfowler** [comment]
I have prior meeting at 6.30 so I'll miss this meet and great. I'll see @gangleri and @ablair08 during day though. Have a good one!

**Comment by d3z** [comment]
Apologies for the last minute change of plans but I won't be out tonight. I'm at work and feeling miserable. 

I'm calling man flu ... it's _that_ serious. 

Annoyingly, I'll be walking past Cafe Nero on my way to the train anyway.
