### ISSUE TITLE
February NodeSchool

### ISSUE THREAD

**Issue by gangleri** [nodeschool/belfast#11]
So first one is over, lets discuss what we'll do for the next one. How does Thursday 25th February suit?

Just say what worked or didn't work, what workshop you'd like to work on at the next. Have a look at http://nodeschool.io/#workshoppers for a list of workshops

**Comment by panloaf** [comment]
That date should suit fine for the venue at least - I don't see any clashes.  Coincidentally, Belfast JS is on the 24th, so that's an interesting pair-up :)

Let me know if there are any significant objections to 25th February.

**Comment by MarkXA** [comment]
If I've managed to get through the core by then I'll probably start working through the ES6 workshops. After that the server-side React one sounds interesting. Since I don't have any specific projects to use Node on, I was also thinking of trying a PR on something like https://github.com/CoderDojo/community-platform/ once I start to feel more confident; that might be a way to work on stuff together?

**Comment by lanazwart** [comment]
Suits me too.

**Comment by bmullan91** [comment]
Sounds good :+1:

**Comment by fitzilla** [comment]
Yep, 25th suits me.

**Comment by chrisfowler** [comment]
25th is good. We could make our sessions on a Tuesday and get 2-for-1 on any pizza.

I'm working my way through the Functional Javascript workshop and was then thinking to have a go with the Jonny-5 stuff after that. Would be nice to have an iot or robotics project to drive some learning.

**Comment by hanrattyjen** [comment]
Is this for anyone? Total newcomer to node.js but want to know more. Ta!

**Comment by gangleri** [comment]
@hanrattyjen this is absolutely for anyone. Just come along with a laptop on the night and we will get you started

**Comment by MarkXA** [comment]
I'm going to miss it I'm afraid. It clashes with an Actual Cultural Event in Coleraine!

**Comment by hanrattyjen** [comment]
Thanks! See you then.

**Comment by gangleri** [comment]
@MarkXA no worries catch you at the next one

**Comment by d3z** [comment]
And can it be ... am I really going to make it out to something ?!?!? Ticket acquired at the 11th hour.

**Comment by gangleri** [comment]
@d3z thanks for coming, great to meet you

**Comment by d3z** [comment]
It was great to get out ! I can hopefully make it a regular occurrence.
