### ISSUE TITLE
Joining Farset

### ISSUE THREAD

**Issue by gangleri** [nodeschool/belfast#13]
If Farset are happy to have us on a regular basis we should add some text to the site to encourage joining Farset and/or donating on the evening. 

@panloaf any thoughts?

**Comment by panloaf** [comment]
I think that's great - I've put a preliminary booking in for 25th February.  We'd really appreciate the support in that fashion.

**Comment by gangleri** [comment]
Cool, I was thinking some text under the Farset logo, wanted to discuss here and agree the text
