### ISSUE TITLE
Sharing twitter account

### ISSUE THREAD

**Issue by gangleri** [nodeschool/belfast#14]
Does anyone have experience with https://grouptweet.com/ or something similar?

I want to share the twitter account with organizers to decentralize running NodeSchool Belfast as much as possible.

**Comment by MarkXA** [comment]
Sharing the password works well enough if you're not going to be sacking people too often.

**Comment by gangleri** [comment]
@MarkXA we're inclusive no sackings :)

**Comment by gangleri** [comment]
We'll just share the password
