### ISSUE TITLE
NodeConf London - free ticket & discount codes

### ISSUE THREAD

**Issue by bmullan91** [nodeschool/belfast#21]
Hey everyone!

Good news, I've spoken with the organiser of [nodeconf london](http://london.nodeconf.com/) - he's provided me with 3 discount codes:
- 1 for 100% off
- 5 for 50% off
- unlimited 25% off

What would be the best way to distribute these fairly? A raffle style with those registered, or perhaps a twitter competition where people tweet nodesschoolbel with a picture / something?

**Comment by panloaf** [comment]
My birthday's the day before it... so it could totally be a birthday
present ;) j/k

Depends on what the preferred outcome is:
1. increase awareness of @nodeschoolbel (twitter competition to increase
RTs and followers)
2. increase membership of the meetup (raffle it with those registered, with
a lead-time for promotion)
or
3. reward those already part of the meetup (raffle it with those
registered, with no lead-time).

Personally, I'd suggest number 2, as it's (slightly) more likely that
someone genuinely invested locally would benefit.

Cheers,
Glenn

**Comment by bmullan91** [comment]
@panloaf @gangleri How's about we put a tweet out today along the lines of:

> One day to go! Make sure to register with tito to be in with a chance to win a free ticket to @nodeconf_london - further discount codes will be issued on the night 🎉
