### ISSUE TITLE
Next Event: Nodeschool International day?

### ISSUE THREAD

**Issue by bmullan91** [nodeschool/belfast#22]
Proposing we take adavantage of http://nodeschool.io/international-day/ and hold our next event on Saturday 21st of May. I know it's a bit short notice... what do we think?

Here's the event repo for more info - https://github.com/nodeschool/international-day

**Comment by panloaf** [comment]
It really is pretty short notice, especially for a Saturday :/  When did they announce it?

**Comment by bmullan91** [comment]
@panloaf I know 😞 - Not sure when it was announced, I only realised a couple of days ago. 

On a plus note, Farset seems to be available (looking at http://www.farsetlabs.org.uk/events/) - and Im sure we could rally some interest if we act swifty with a few tweets etc.

@gangleri what do you reckon 😄

**Comment by gangleri** [comment]
Closing this as the date has past
